version: "3.0"
volumes:
  mds_data:
    driver: local
  auth_data:
    driver: local
services:
  mds-db:
    container_name: mds-db
    image: postgres:latest
    volumes:
      - mds_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mdsportal
      POSTGRES_USER: mdsadmin
      POSTGRES_PASSWORD: mdsadmin
    networks:
      - mds-network
  auth-db:
    container_name: auth-db
    image: postgres:latest
    volumes:
      - auth_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    networks:
      - mds-network
  keycloak:
    container_name: mds-auth
    image: jboss/keycloak:16.1.1
    restart: on-failure
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: auth-db
      DB_PORT: 5432
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: keycloak
      PROXY_ADDRESS_FORWARDING: "true"
      KEYCLOAK_FRONTEND_URL: http://mds.intranet/auth
      KEYCLOAK_USER: keycloak
      KEYCLOAK_PASSWORD: keycloak
      KEYCLOAK_IMPORT: /tmp/realm-export.json
    volumes:
      - ./realm-export.json:/tmp/realm-export.json
    depends_on:
      - auth-db
    networks:
      - mds-network
  mds-api:
    container_name: mds-api
    image: ghcr.io/macroscode/mds-api:latest
    restart: on-failure
    pull_policy: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://mds-db:5432/mdsportal
      SPRING_DATASOURCE_USERNAME: mdsadmin
      SPRING_DATASOURCE_PASSWORD: mdsadmin
      KEYCLOAK_REALM: "http://mds.intranet/auth/realms/mds-auth"
      KEYCLOAK_ALLOWED_ORIGINS: ""
      ENCRYPTION_SEED: "my-secret-seed"
    depends_on:
      - mds-db
      - keycloak
    networks:
      - mds-network
  mds-ui:
    container_name: mds-ui
    hostname: mds.intranet
    image: ghcr.io/macroscode/mds-ui:latest
    restart: on-failure
    pull_policy: always
    ports:
      - 80:80
    depends_on:
      - mds-api
    networks:
      - mds-network
    volumes:
      - ./environment.json:/usr/share/nginx/html/assets/environment.json
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
networks:
  mds-network:
    driver: bridge