version: "3.0"
volumes:
  mds_data:
    driver: local
  auth_data:
    driver: local
services:
  mds-db:
    image: postgres:latest
    volumes:
      - mds_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mdsportal
      POSTGRES_USER: mdsadmin
      POSTGRES_PASSWORD: mdsadmin
    networks:
      - mds-network
  auth-db:
    image: postgres:latest
    volumes:
      - auth_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    networks:
      - mds-network

  keycloak:
    container_name: mds-auth
    image: jboss/keycloak:16.1.1
    restart: on-failure
    environment:
      DB_ADDR: http://auth-db
      DB_PORT: 5432
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: keycloak
      PROXY_ADDRESS_FORWARDING: "true"
      KEYCLOAK_FRONTEND_URL: https://mds.coffeeandpaste.co/auth
      KEYCLOAK_USER: keycloak
      KEYCLOAK_PASSWORD: keycloak
      # KEYCLOAK_IMPORT: /tmp/realm-export.json
    # volumes:
      # - ./keycloak-realm/realm-export.json:/tmp/realm-export.json
    depends_on:
      - auth-db
    networks:
      - mds-network
  mds-api:
    container_name: mda-api
    build: ./api/.
    restart: on-failure
    pull_policy: build
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://mds-db:5432/mdsportal
      SPRING_DATASOURCE_USERNAME: mdsadmin
      SPRING_DATASOURCE_PASSWORD: mdsadmin
      KEYCLOAK_REALM: "https://mds.coffeeandpaste.co/auth/realms/mds-auth"
      KEYCLOAK_ALLOWED_ORIGINS: ""
      ENCRYPTION_SEED: "8ad28685c68d2db9ebc6a4c6c8277678"
    depends_on:
      - mds-db
    networks:
      - mds-network
  mds-ui:
    container_name: mds-ui
    build: ./ui/.
    restart: on-failure
    pull_policy: build
    ports:
      - 4200:80
    depends_on:
      - mds-api
    networks:
      - mds-network
networks:
  mds-network:
    # driver: bridge