name: Docker Build and Publish

on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - test

env:
  DOCKER_REGISTRY: docker.pkg.github.com
  GITHUB_USERNAME: ${{ secrets.GITHUB_USERNAME }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ env.GITHUB_USERNAME }}
          password: ${{ env.GITHUB_TOKEN }}

      - name: Build and publish Docker
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_REGISTRY }}/${{ github.repository }}/image1:${{ github.sha }}, ${{ env.DOCKER_REGISTRY }}/${{ github.repository }}/image2:${{ github.sha }}

      - name: Docker digest
        run: |
          echo ${{ steps.docker_build.outputs.digests }}
